#配置数据库连接信息
spring:
  application:
    name: web-first-projrct02
  #数据库的连接信息
  datasource:
    url: jdbc:mysql://mysql:3306/tlias
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123
  servlet:
    multipart:
      #最大单个文件大小
      max-file-size: 10MB
      #最大请求大小(包括所有文件和表单数据)
      max-request-size: 100MB

#mybatis相关配置文件
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    #开启驼峰命名映射开关   create_Time(数据库属性名)和createTime(对象属性)的对应
    map-underscore-to-camel-case: true

#配置事务管理日志级别
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: java-web-baicai
    region: cn-beijing
